# Generated by Django 2.2.3 on 2019-08-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idEstadoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.EstadoUsuario'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idTipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.TipoUsuario'),
        ),
    ]
