# Generated by Django 2.2.3 on 2019-09-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_auto_20190905_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadousuario',
            name='descripcion',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente de activación'), ('Actuvo', 'Activo'), ('Suspendido', 'Suspendido'), ('Eliminado', 'Eliminado')], max_length=50, null=True),
        ),
    ]
