# Generated by Django 2.2.3 on 2019-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_auto_20190908_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idEstadoUsuario',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de activación'), ('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Eliminado', 'Eliminado')], default='Pendiente', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idTipoUsuario',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Visitante', 'Visitante')], default='Visitante', max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='EstadoUsuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
