# Generated by Django 2.2.3 on 2019-09-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_auto_20190908_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefonoNumero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
