# Generated by Django 2.2.3 on 2019-09-03 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sitio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='fechaAlta',
            new_name='fechaAltaDenuncia',
        ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='fechaBaja',
            new_name='fechaBajaDenuncia',
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenidoRespuesta', models.TextField(blank=True, null=True)),
                ('fechaBajaRespuesta', models.DateTimeField(blank=True, default=None, null=True)),
                ('fechaAltaRespuesta', models.DateTimeField(blank=True, default=None, null=True)),
                ('idComentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sitio.Comentario')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
