# Generated by Django 2.2.3 on 2019-09-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0002_auto_20190903_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estadoPublicacion',
            field=models.CharField(blank=True, choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador'), ('Denunciado', 'Denunciado'), ('Eliminado', 'Eliminado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipoPublicacion',
            field=models.CharField(blank=True, choices=[('Electronica', 'Electronica'), ('Equipamiento', 'Equipamiento'), ('Maquinarias', 'Maquinarias'), ('Telefonia', 'Telefonia'), ('Electronica', 'Electronica'), ('Informatica', 'Informatica'), ('AudioVideo', 'Audio y video'), ('Juegos', 'Juegos'), ('Electrodomesticos', 'Electrodomesticos'), ('Amoblamientos', 'Amoblamientos'), ('Herramientas', 'Herramientas'), ('Bazar', 'Bazar')], max_length=50, null=True),
        ),
    ]
