# Generated by Django 2.2.3 on 2019-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0003_auto_20190906_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='precio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
