# Generated by Django 2.2.3 on 2019-09-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0004_publicacion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='localidad',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='provincia',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
