# Generated by Django 2.2.3 on 2019-09-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0006_auto_20190907_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='localidadPublicacion',
        ),
    ]
