# Generated by Django 2.0.13 on 2019-09-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0007_remove_publicacion_localidadpublicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='provinciaPublicacion',
        ),
    ]
