# Generated by Django 2.2.6 on 2019-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0007_remove_publicacion_localidadpublicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='provinciaPublicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
