# Generated by Django 2.2.6 on 2019-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0008_auto_20191007_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='images/'),
        ),
    ]
