# Generated by Django 2.0.13 on 2019-10-12 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0010_auto_20191007_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntaje',
            name='idPublicacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Sitio.Publicacion'),
            preserve_default=False,
        ),
    ]
