# Generated by Django 2.0.13 on 2019-10-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0010_auto_20191012_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenidoComentario',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaComentario',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
