# Generated by Django 2.0.13 on 2019-10-30 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0011_auto_20191014_2242'),
        ('Sitio', '0010_auto_20191007_1627'),
    ]

    operations = [
    ]
